name: "Code for Life - Workspace - Download And Run Job Script"
description: "Download a job script from the workspace and run it."
inputs:
  branch:
    description: "The branch on the workspace repo."
    required: true
    default: "main"
  args:
    description: "The arguments to pass to the script."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
      with:
        branch: ${{ inputs.branch }}
        path: .github/scripts/cfl_ascii_art.sh
        type: bash

    - uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
      with:
        branch: ${{ inputs.branch }}
        path: .github/scripts/general.sh
        type: bash

    - uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
      with:
        branch: ${{ inputs.branch }}
        path: .github/scripts/github.sh
        type: bash

    - id: make-script-path
      shell: bash
      run: |
        workflow="$(
          echo "${{ github.workflow_ref }}" |
            sed -E 's/^.+\/.github\/workflows\/(.+)\.(yml|yaml)@.+$/\1/'
        )"

        job="$(echo "${{ github.job }}" | sed 's/-/_/g')"

        script_path=".github/scripts/jobs/${workflow}/${job}.sh"

        echo "value=$script_path" >> $GITHUB_OUTPUT

    - uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
      with:
        branch: ${{ inputs.branch }}
        path: ${{ steps.make-script-path.outputs.value }} 
        type: bash

    - shell: bash
      run: |
        .github/scripts/cfl_ascii_art.sh
        ${{ steps.make-script-path.outputs.value }} "${{ inputs.args }}"
