name: "Code for Life - Workspace - Download And Run Job Script"
description: "Download a job script from the workspace and run it."
inputs:
  branch:
    description: "The branch on the workspace repo."
    required: true
    default: "main"
  args:
    description: "The arguments to pass to the script."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        M='\e[35m' # magenta
        C='\e[36m' # cyan
        Y='\e[33m' # yellow
        RESET='\e[0m'

        echo -en "
          ${M}_____          ${Y}_        ______           _      ${M}_  ${C}__
         ${M}/ ____|        ${Y}| |      |  ____|         | |    ${M}(_)${C}/ _|
        ${M}| |     ${C}___   ${Y}__| | ${M}___  ${Y}| |__ ${M}___  ${C}_ __  ${Y}| |     ${M}_| ${C}|_ ${Y}___
        ${M}| |    ${C}/ _ \\ ${Y}/ _\` |${M}/ _ \\ ${Y}|  __${M}/ _ \\"
        echo -e "${C}| '__| ${Y}| |    ${M}| |  ${C}_${Y}/ _ \\
        ${M}| |___${C}| (_) | ${Y}(_| |  ${M}__/ ${Y}| | ${M}| (_) ${C}| |    ${Y}| |____${M}| | ${C}|${Y}|  __/
         ${M}\\_____${C}\\___/ ${Y}\\__,_|${M}\\___| ${Y}|_|  ${M}\\___/${C}|_|    ${Y}|______${M}|_|${C}_| ${Y}\\___|
        ${RESET}"

    - uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
      with:
        branch: ${{ inputs.branch }}
        path: .github/scripts/general.sh
        type: bash

    - uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
      with:
        branch: ${{ inputs.branch }}
        path: .github/scripts/github.sh
        type: bash

    - id: make-script-path
      shell: bash
      run: |
        workflow="$(
          echo "${{ github.workflow_ref }}" |
            sed -E 's/^.+\/.github\/workflows\/(.+)\.(yml|yaml)@.+$/\1/'
        )"

        job="$(echo "${{ github.job }}" | sed 's/-/_/g')"

        script_path=".github/scripts/jobs/${workflow}/${job}.sh"

        echo "value=$script_path" >> $GITHUB_OUTPUT

    - uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
      with:
        branch: ${{ inputs.branch }}
        path: ${{ steps.make-script-path.outputs.value }} 
        type: bash

    - shell: bash
      run: ${{ steps.make-script-path.outputs.value }} "${{ inputs.args }}"
