name: "Code for Life - Service - Release"
description: "Release a service deployment to GitHub."
inputs:
  cfl-bot-gh-token:
    description: "The GitHub token of the CFL bot."
    required: true
  deploy-artifact-path:
    description: "The path of the deploy artifact."
    required: false
    default: ".deploy"
  deploy-zip-path:
    description: "The path of the deploy.zip."
    required: false
    default: "../deploy.zip"
runs:
  using: composite
  steps:
    - name: 🛫 Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.cfl-bot-gh-token }}
        fetch-depth: 0

    - name: 📥 Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: build

    - name: 📥 Download Deploy Artifact
      uses: actions/download-artifact@v4
      with:
        name: deploy
        path: ${{ inputs.deploy-artifact-path }}

    - name: 📁 Zip Deploy Files
      working-directory: ${{ inputs.deploy-artifact-path }}
      shell: bash
      run: zip --quiet --recurse-paths ${{ inputs.deploy-zip-path }} .
