name: "Code for Life - Workspace - Process Submodules"
description: "Process each submodule in the workspace."
inputs:
  branch:
    description: "The branch on the workspace repo."
    required: true
    default: "main"
  pre-processing:
    description: "A callback right before any submodules are processed."
    required: true
    default: return 0
  pre-process:
    description: "A callback right before each submodule is processed."
    required: true
    default: return 0
  process:
    description: "A callback which processes each submodule."
    required: true
  post-process:
    description: "A callback right after each submodule is processed."
    required: true
    default: return 0
  post-processing:
    description: "A callback right after all submodules are processed."
    required: true
    default: return 0
runs:
  using: composite
  steps:
    - name: 📥 Download .gitmodules
      uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
      with:
        branch: ${{ inputs.branch }}
        path: .gitmodules
        save-to: .gitmodules

    - name: ⚙️ Process Submodules
      shell: bash
      run: |
        readarray -t names < <(
          grep '\[submodule ".*"\]' .gitmodules |
          sed -E 's/\[submodule "(.*)"\]/\1/'
        )

        function get_value() {
          local name="$1"
          local key="$2"

          git config --file .gitmodules "submodule.$name.$key"
        }

        function pre_process() {
          ${{ inputs.pre-process }}
        }
        function process() {
          ${{ inputs.process }}
        }
        function post_process() {
          ${{ inputs.post-process }}
        }

        ${{ inputs.pre-processing }}

        for name in "${names[@]}"; do
          path=$(get_value "$name" "path")
          url=$(get_value "$name" "url")

          pre_process "$name" "$path" "$url"
          process "$name" "$path" "$url"
          post_process "$name" "$path" "$url"
        done

        ${{ inputs.post-processing }}
