name: Backend

on:
  workflow_call:
    inputs:
      python-version:
        description: "The Python version to set up."
        type: number
        required: false
        default: 3.12
      # TODO: remove this after restructure and standardize source path.
      source-path:
        description: "The path to the source files."
        type: string
        required: false
        default: "api"
      postgres-db:
        description: "The postgres database to test against."
        type: string
        required: false
        default: "db"
      postgres-version:
        description: "The postgres version to set up."
        type: number
        required: false
        default: 16 # TODO: set to 17
    secrets: # All secrets should not be required to support contributors.
      CODECOV_TOKEN:
        description: "The token used to gain access to Codecov."
        required: false
      CFL_BOT_GH_TOKEN:
        description: "The CFL-bot's GitHub token. Used to release."
        required: false

jobs:
  test:
    uses: ocadotechnology/codeforlife-workspace/.github/workflows/test-python-code.yaml@main
    secrets: inherit
    with:
      python-version: ${{ inputs.python-version }}
      source-path: ${{ inputs.source-path }}
      postgres-db: ${{ inputs.postgres-db }}
      postgres-version: ${{ inputs.postgres-version }}

  build:
    runs-on: ubuntu-latest
    needs: [test]
    # Build if:
    #  - the repo's owner is Ocado Tech.
    #  - the repo is not the backend template.
    #  - a change is made to the default branch.
    if: |
      github.repository_owner_id == 2088731 &&
      github.repository_id != 610204172 &&
      github.ref_name == github.event.repository.default_branch
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 📝 Overwrite RDS Parameters
        run: |
          if [ -f .deploy/rds.json ]; then
            echo $(
              jq '
                .databaseName = "${APP_ID}" |
                .schemaName = "app" |
                .engine = "POSTGRES_'${{ inputs.postgres-version }}'"
              ' .deploy/rds.json
            ) > .deploy/rds.json
          fi

      - name: 📝 Overwrite Static Parameters
        run: |
          if [ -f .deploy/static.json ]; then
            echo $(
              jq '
                .artifactUrl = "${STATIC_NEXUS_URL}" |
                .assetsPrefix = "static/" |
                .bucket = "static"
              ' .deploy/static.json
            ) > .deploy/static.json
          fi

      - name: 📤 Upload Deploy Artifact
        uses: ocadotechnology/codeforlife-workspace/.github/actions/service/upload-deploy-artifact@main
        with:
          runtime-type: python
          runtime-version: ${{ inputs.python-version }}
          variables: |
            APP_ID = "${APP_ID}"
            APP_VERSION = "${APP_VERSION}"
            DJANGO_SETTINGS_MODULE = "settings"
            DEBUG = "0"
            SERVICE_PROTOCOL = "https"
            SERVICE_PORT = "443"
            MAIL_ENABLED = "1"
            STATIC_URL = "${STATIC_URL}"
            AWS_STORAGE_BUCKET_NAME = "${AWS_STORAGE_BUCKET_NAME}"
            ENV = "${ENV}"

      - name: 🐍 Set up Python ${{ inputs.python-version }} Environment
        uses: ocadotechnology/codeforlife-workspace/.github/actions/python/setup-environment@main
        with:
          python-version: ${{ inputs.python-version }}
          checkout: false

      - name: 🏗️ Generate requirements.txt
        run: |
          pipenv requirements > requirements.txt
          sed -i '1d' requirements.txt # Remove 1st line (contains package index)

      - name: 🏗️ Collect Static Files
        run: pipenv run python ./manage.py collectstatic --noinput --clear

      - name: 📤 Upload Build Artifact
        uses: ocadotechnology/codeforlife-workspace/.github/actions/service/upload-build-artifact@main
        with:
          path: |
            requirements.txt
            static/

  # release:
  #   needs: [build]
  #   uses: ocadotechnology/codeforlife-workspace/.github/workflows/release-service.yaml@main
  #   secrets: inherit
  release:
    concurrency: release
    runs-on: ubuntu-latest
    needs: [build]
    env:
      DEPLOY_ARTIFACT_PATH: ".deploy"
    steps:
      # - name: 🛫 Set up Release
      #   uses: ocadotechnology/codeforlife-workspace/.github/actions/service/setup-release@main
      #   with:
      #     cfl-bot-gh-token: ${{ secrets.CFL_BOT_GH_TOKEN }}

      - name: 🛫 Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CFL_BOT_GH_TOKEN }}
          fetch-depth: 0

      - name: 📥 Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: 📥 Download Deploy Artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: ${{ env.DEPLOY_ARTIFACT_PATH }}

      - name: 📁 Zip Deploy Files
        working-directory: ${{ env.DEPLOY_ARTIFACT_PATH }}
        run: zip --quiet --recurse-paths ../deploy.zip .

      # Action end

      - name: 📁 Zip Static Files
        working-directory: static
        run: zip --quiet --recurse-paths ../static.zip .

      - name: 📁 Zip Dotenv Files
        run: zip --quiet --recurse-paths .env.zip .env

      # - name: 🚀 Publish Semantic Release
      #   uses: ocadotechnology/codeforlife-workspace/.github/actions/service/release@main
      #   with:
      #     cfl-bot-gh-token: ${{ secrets.CFL_BOT_GH_TOKEN }}
      #     releaserc-path: backend

      - name: 📥 Download Release Candidate Configuration
        run: wget https://raw.githubusercontent.com/ocadotechnology/codeforlife-workspace/refs/heads/main/backend.releaserc.json -O .releaserc.json

      - name: 🚀 Publish Semantic Release
        uses: ocadotechnology/codeforlife-workspace/.github/actions/github/release@main
        with:
          cfl-bot-gh-token: ${{ secrets.CFL_BOT_GH_TOKEN }}
          checkout: false
