name: Code Workspace

on:
  push:
    paths:
      - "codeforlife.code-workspace"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: 🔎 Check JSON Loads
        run: |
          python -c "
          import json

          with open("codeforlife.code-workspace", "r", encoding="utf-8") as code_workspace:
            json.load(code_workspace)
          "
