name: Frontend

on:
  workflow_call:
    inputs:
      node-version:
        description: "The Node.js version to set up."
        type: number
        required: false
        default: 18
    secrets: # All secrets should not be required to support contributors.
      CODECOV_TOKEN:
        description: "The token used to gain access to Codecov."
        required: false
      CFL_BOT_GH_TOKEN:
        description: "The CFL-bot's GitHub token. Used to release."
        required: false

jobs:
  test:
    uses: ocadotechnology/codeforlife-workspace/.github/workflows/test-javascript-code.yaml@main
    secrets: inherit
    with:
      node-version: ${{ inputs.node-version }}

  build:
    runs-on: ubuntu-latest
    needs: [test]
    # Build if:
    #  - the repo's owner is Ocado Tech.
    #  - the repo is not the frontend template.
    #  - a change is made to the default branch.
    if: |
      github.repository_owner_id == 2088731 &&
      github.repository_id != 841979065 &&
      github.ref_name == github.event.repository.default_branch
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4

      - name: 📤 Upload Deploy Artifact
        uses: ocadotechnology/codeforlife-workspace/.github/actions/service/upload-deploy-artifact@main
        with:
          runtime-type: nodejs
          runtime-version: ${{ inputs.node-version }}
          variables: |
            NODE_ENV = "production"
            MODE = "${MODE}"

      - name: 🌐 Set up JavaScript ${{ inputs.node-version }} Environment
        uses: ocadotechnology/codeforlife-workspace/.github/actions/javascript/setup-environment@main
        with:
          node-version: ${{ inputs.node-version }}
          install-args: --production=true
          checkout: false

      - name: 🏗️ Build App
        run: yarn run vite build --outDir dist/client && yarn run vite build --ssr src/entry-server.tsx --outDir dist/server

      - name: 📤 Upload Build Artifact
        uses: ocadotechnology/codeforlife-workspace/.github/actions/service/upload-build-artifact@main
        with:
          path: dist/

  release:
    concurrency: release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: 🛫 Set up Release
        uses: ocadotechnology/codeforlife-workspace/.github/actions/service/setup-release@main
        with:
          cfl-bot-gh-token: ${{ secrets.CFL_BOT_GH_TOKEN }}

      - name: 📁 Zip Distribution Files
        run: zip --quiet --recurse-paths dist.zip dist

      - name: 🚀 Publish Semantic Release
        uses: ocadotechnology/codeforlife-workspace/.github/actions/service/release@main
        with:
          cfl-bot-gh-token: ${{ secrets.CFL_BOT_GH_TOKEN }}
          rc-path: frontend.releaserc.json
