name: Issues

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created, edited]
  schedule:
    - cron: "0 9 * * *" # Every day at 9am UTC.
  workflow_dispatch:
  workflow_call:
    secrets:
      CFL_BOT_GH_TOKEN:
        description: "The CFL-bot's GitHub token. Used to comment."
        required: false

jobs:
  opened:
    runs-on: ubuntu-22.04
    if: |
      github.repository_owner_id == 2088731 &&
      github.event_name == 'issues' &&
      github.event.action == 'opened' &&
      github.event.issue.user.login != 'cfl-bot' &&
      !contains(github.event.issue.labels.*.name, 'bot ignore')
    env:
      GH_TOKEN: ${{ secrets.CFL_BOT_GH_TOKEN }}
    steps:
      - name: 九꽲잺 Download and Write Was-Opened Comment
        uses: ocadotechnology/codeforlife-workspace/.github/actions/bot/comment-on-issue@main
        with:
          download-issue-comment-path: was-opened.md

  comment-created-or-edited:
    runs-on: ubuntu-22.04
    if: |
      github.repository_owner_id == 2088731 &&
      github.event_name == 'issue_comment' &&
      !github.event.issue.pull_request &&
      contains(fromJSON('["created", "edited"]'), github.event.action) &&
      github.event.comment.user.login != 'cfl-bot' &&
      !contains(github.event.issue.labels.*.name, 'bot ignore')
    env:
      GH_TOKEN: ${{ secrets.CFL_BOT_GH_TOKEN }}
      SCRIPT_PATH: .github/scripts/issue/comment_created_or_edited.sh
      # String variables.
      REPO: "${{ github.repository }}"
      REPO_OWNER: "${{ github.repository_owner }}"
      REPO_NAME: "${{ github.event.repository.name }}"
      ISSUE_NUMBER: "${{ github.event.issue.number }}"
      ISSUE_NODE_ID: "${{ github.event.issue.node_id }}"
      ISSUE_ASSIGNEES_LENGTH: "${{ github.event.issue.assignees.length }}"
      USER_NODE_ID: "${{ github.event.comment.user.node_id }}"
      USER_LOGIN: "${{ github.event.comment.user.login }}"
      # Boolean variables.
      ISSUE_IS_OPEN: "${{ github.event.issue.state == 'open' }}"
      ISSUE_HAS_COMMENTER_ASSIGNED: "${{ contains(github.event.issue.assignees.*.id, github.event.comment.user.id) }}"
    steps:
      - name: 游닌 Download General Script
        uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
        with:
          path: .github/scripts/general.sh
          type: bash

      - name: 游닌 Download GitHub Script
        uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
        with:
          path: .github/scripts/github.sh
          type: bash

      - name: 游닌 Download Workspace Script
        uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
        with:
          path: .github/scripts/workspace.sh
          type: bash

      - name: 游닌 Download Comment-Created-Or-Edited Script
        uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
        with:
          path: ${{ env.SCRIPT_PATH }}
          type: bash

      - name: 游끢 Run Comment-Created-Or-Edited Script
        run: ${{ env.SCRIPT_PATH }} "${{ github.event.comment.body }}"

  inactive:
    runs-on: ubuntu-22.04
    if: |
      github.repository_owner_id == 2088731 &&
      contains(fromJSON('["schedule", "workflow_dispatch"]'), github.event_name)
    env:
      GH_TOKEN: ${{ secrets.CFL_BOT_GH_TOKEN }}
      ONE_WEEK_MD: 1-week.md
      TWO_WEEKS_MD: 2-weeks.md
      THREE_WEEKS_MD: 3-weeks.md
      SCRIPT: process.sh
    steps:
      - name: 游닌 Download 1-Week Comment
        uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
        with:
          path: .github/comments/issue/inactive/1-week.md
          save-to: ${{ env.ONE_WEEK_MD }}

      - name: 游닌 Download 2-Weeks Comment
        uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
        with:
          path: .github/comments/issue/inactive/2-weeks.md
          save-to: ${{ env.TWO_WEEKS_MD }}

      - name: 游닌 Download 3-Weeks Comment
        uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
        with:
          path: .github/comments/issue/inactive/3-weeks.md
          save-to: ${{ env.THREE_WEEKS_MD }}

      - name: 游닌 Download Script
        uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
        with:
          path: .github/scripts/issue/unassign_inactive_assignees.sh
          save-to: ${{ env.SCRIPT }}
          type: bash

      - name: 丘뙖잺 Unassign Inactive Contributors
        uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/process-submodules@main
        with:
          pre-processing: process "${{ github.event.repository.name }}"
          process: source ${{ env.SCRIPT }}
