name: Monitor Python Release

on:
  workflow_call:
    inputs:
      python-version:
        description: "The Python version to set up."
        type: number
        required: true
      snyk-config-path:
        description: "The path of the Snyk config file in the workspace."
        type: string
        required: false
        default: "backend/.snyk"
    secrets:
      CFL_BOT_GH_TOKEN:
        description: "The CFL-bot's GitHub token. Used to release."
        required: true
      SNYK_TOKEN:
        description: "The token used to authenticate with Snyk API."
        required: true

jobs:
  monitor:
    concurrency: release
    runs-on: ubuntu-22.04
    steps:
      - name: 🐍 Set up Python ${{ inputs.python-version }} Environment
        uses: ocadotechnology/codeforlife-workspace/.github/actions/python/setup-environment@main
        with:
          python-version: ${{ inputs.python-version }}

      - name: 🔎 Monitor Open-Source Vulnerabilities and License Issues
        uses: ocadotechnology/codeforlife-workspace/.github/actions/snyk/monitor-release@main
        with:
          gh-token: ${{ secrets.CFL_BOT_GH_TOKEN }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}
          snyk-config-path: ${{ inputs.snyk-config-path }}
          snyk-project-environment: backend
          snyk-add-monitor-args: --command=.venv/bin/python
